csv_path:           # CCV file with data information
in_channel: 2       # Number of input channels (e.g. 1 for grey-scale, 3 for rgb).
out_channel: 1      # Number of output channels.
base_output:        # Base output path for saving of results.
optimizer: Adam     # Optimizer to be used, implemented optimizers are "AdamW", "Adam", "SGD".
activation: prelu   # Activation function to be used, check activations.py or _init_activation for available activation functions.
length: 3           # Number of consecutive residual blocks in each layer in the UNet structure.
features:           # Number of features in down- / upsampling path
- 16
- 32
- 64
- 128
- 256
lr: 1.0e-04
dropout: 0.2        # Dropout
batch_size: 128     # Batch size
num_workers: 8      # Workers used by dataloader
num_threads: 8      # Number of threads used by the script
val_num: 4          # Number of examples plotted for validation
pin_memory: true
comment:            # Freeform to give additional context to saving file.
